// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const path = require('path');

const PREFIX = '/PrimeForgeApiPortal';

// Read services definition. Each entry should have at least a `name` and
// `title` (optional) and `url` pointing to the JSON OpenAPI spec.
const services = require('./services.json');

// Build Redoc specs array. The `spec` property points to the local file
// generated by `npm run update-specs`. The `route` defines the URL within
// your portal where the API will appear. Each spec will render a full
// Redoc page with its own search and navigation on the left.
const specs = services.map((svc) => ({
  spec: path.join(__dirname, 'openapi', `${svc.name}.json`),
  route: `${PREFIX}/api/${svc.name}`,
  id: svc.name,
}));

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'PrimeForge API Portal',
  tagline: 'API documentation for PrimeForge microservices',
  // Edit the `url` and `baseUrl` below to match your deployment. When
  // deploying to GitHub Pages under <org>/<repo>, `url` should be
  // `https://<org>.github.io` and `baseUrl` should be `/<repo>/`. The
  // defaults here assume a repo named `nestjs-doc-site` under `your-github-org`.
  url: 'https://darkhorseone.github.io',
  baseUrl: `${PREFIX}/`,
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  // The same logo is used as the favicon. You can replace this with
  // a proper ICO or PNG file by creating it under static/img/.
  favicon: 'img/logo.svg',
  organizationName: 'darkhorseone', // Usually your GitHub org/user name.
  projectName: 'PrimeForgeApiPortal', // Usually your repo name.
  presets: [
    [
      '@docusaurus/preset-classic',
      /** @type {import('@docusaurus/preset-classic').Options} */ ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          routeBasePath: 'docs',
          editUrl: 'https://github.com/DarkhorseOne/PrimeForgeApiPortal/tree/main/',
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
    [
      'redocusaurus',
      {
        specs: specs,
        theme: {
          primaryColor: '#5B21B6',
        },
      },
    ],
  ],
  themeConfig: {
    navbar: {
      title: 'PrimeForge API Portal',
      logo: {
        alt: 'API Logo',
        src: 'img/logo.svg',
      },
      items: [
        { to: '/', label: 'Home', position: 'left' },
        { to: '/docs/intro', label: 'Guides', position: 'left' },
        // Dynamically generate nav items for each service. These point to the Redoc pages.
        ...services.map((svc) => ({
          to: `/api/${svc.name}`,
          label: svc.title || svc.name,
          position: 'left',
        })),
        {
          href: 'https://github.com/DarkhorseOne/PrimeForgeApiPortal',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Services',
          items: services.map((svc) => ({
            label: svc.title || svc.name,
            to: `/api/${svc.name}`,
          })),
        },
        {
          title: 'Community',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/DarkhorseOne/PrimeForgeApiPortal',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} DarkhorseOne Ltd.`,
    },
  },
};

module.exports = config;